name: Test workflow
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [ arc-runner-test-arm-spot ]
    name: Test
    steps:
      - name: Test
        run: |
          cat /etc/os-release
          uname -p