name: Test workflow
run-name: Test workflow on arm
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [ arc-runner-arm-lightweight ]
    name: Test
    steps:
      - name: Show /etc/os-release
        run: cat /etc/os-release
      - name: Call uname -p
        run: uname -p
      - name: Proc info
        run: cat /proc/cpuinfo
      - name: Check docker
        run: |
          docker version
          docker ps